// Ground truth data for BATTU validation.
//
// Every value in GROUND_TRUTH can be independently checked against:
//   - Yahoo Finance       (finance.yahoo.com)
//   - Macrotrends         (macrotrends.net)
//   - SEC EDGAR           (sec.gov)
//   - Koyfin free tier    (koyfin.com)
//
// First-time setup workflow:
//   1. Run `pnpm seed:groundtruth` to populate from Yahoo Finance
//   2. Manually verify high-value fields (EE/ANR/LIQ) against a second source
//   3. Run `pnpm validate` against the live BATTU API
//
// Re-running the seed will OVERWRITE the GROUND_TRUTH block between the
// markers below. Hand-edited values inside the block will be lost. Edits
// outside the markers (types, helpers, tolerance) are preserved.

export type ToleranceBand = 'price' | 'financial' | 'ratio' | 'estimate' | 'liq'

export const TOLERANCE: Record<ToleranceBand, number> = {
  price:     0.01,  // 1%   — prices drift, snapshot timing causes small variance
  financial: 0.005, // 0.5% — should match filings almost exactly
  ratio:     0.03,  // 3%   — methodology differences (TTM vs FY, etc.)
  estimate:  0.05,  // 5%   — consensus aggregation differences across sources
  liq:       0.05,  // 5%   — Claude extraction has minor variance on prose fields
}

export interface GroundTruthField {
  value: number | null    // null = SKIP (field not applicable to this ticker)
  band: ToleranceBand
  source: string          // 'yahoo' | 'yahoo-seed' | 'macrotrends' | 'edgar' | 'koyfin' | 'manual'
  verifiedAt: string      // ISO date string
  notes?: string
}

export interface GroundTruthRecord {
  ticker: string

  // ── DES fields ──
  marketCapB:           GroundTruthField  // billions USD
  sharesOutstandingM:   GroundTruthField  // millions
  peRatioTTM:           GroundTruthField
  epsTTM:               GroundTruthField
  dividendYield:        GroundTruthField  // decimal — 0.005 = 0.5%
  beta:                 GroundTruthField

  // ── FA fields (most recent fiscal year) ──
  revenueB:             GroundTruthField  // billions USD
  grossMargin:          GroundTruthField  // decimal
  operatingMargin:      GroundTruthField
  netMargin:            GroundTruthField
  totalDebtB:           GroundTruthField
  cashAndEquivB:        GroundTruthField

  // ── EE fields (next 12 months consensus) ──
  epsEstimateNTM:       GroundTruthField
  revenueEstimateNTMB:  GroundTruthField

  // ── ANR fields ──
  analystConsensus:     GroundTruthField  // 1=Strong Sell ... 5=Strong Buy
  priceTargetConsensus: GroundTruthField

  // ── HP fields ──
  closePrice1YrAgo:     GroundTruthField  // adjusted close 1yr before HP_REFERENCE_DATE

  // ── LIQ fields (biotechs only — others SKIP) ──
  liqCashRunwayQtrs:    GroundTruthField
  liqTotalLiquidityB:   GroundTruthField
}

/**
 * Tickers under validation. Chosen to cover sectors, sizes, edge cases:
 *  AAPL/MSFT/NVDA  — mega cap tech, best-validated public data
 *  BIIB/MRNA       — biotechs with shelf registrations (LIQ screen test)
 *  JPM             — banks (different financial structure)
 *  TSLA            — volatility / consumer auto
 *  META            — ad-tech
 *  AMZN            — e-commerce / cloud
 *  XOM             — energy
 *  SPY             — ETF (most fields N/A)
 *  PLTR            — small-mid cap, good estimates test
 */
export const TICKERS = [
  'AAPL', 'MSFT', 'NVDA', 'BIIB', 'MRNA', 'JPM',
  'TSLA', 'META', 'AMZN', 'XOM',  'SPY',  'PLTR',
] as const

export type Ticker = typeof TICKERS[number]

/**
 * Reference date for the HP (historical price) field.
 * closePrice1YrAgo expects the adjusted close for exactly one year before this date.
 */
export const HP_REFERENCE_DATE = '2025-05-20'

/** Helper for constructing a ground-truth field. */
function gt(
  value: number | null,
  band: ToleranceBand,
  source: string,
  verifiedAt: string,
  notes?: string,
): GroundTruthField {
  return { value, band, source, verifiedAt, ...(notes ? { notes } : {}) }
}

// ── GROUND_TRUTH START ──
// Auto-generated by seedFetcher. Anything between START and END markers will be
// overwritten on the next `pnpm seed:groundtruth` run.
export const GROUND_TRUTH: Record<Ticker, GroundTruthRecord> = {
  AAPL: {
    ticker: 'AAPL',
    marketCapB            : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    sharesOutstandingM    : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    peRatioTTM            : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    epsTTM                : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    dividendYield         : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    beta                  : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    revenueB              : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    grossMargin           : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    operatingMargin       : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    netMargin             : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    totalDebtB            : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    cashAndEquivB         : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    epsEstimateNTM        : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    revenueEstimateNTMB   : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    analystConsensus      : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    priceTargetConsensus  : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    closePrice1YrAgo      : gt(    null, 'price'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    liqCashRunwayQtrs     : gt(    null, 'liq'        , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    liqTotalLiquidityB    : gt(    null, 'liq'        , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
  },
  MSFT: {
    ticker: 'MSFT',
    marketCapB            : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    sharesOutstandingM    : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    peRatioTTM            : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    epsTTM                : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    dividendYield         : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    beta                  : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    revenueB              : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    grossMargin           : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    operatingMargin       : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    netMargin             : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    totalDebtB            : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    cashAndEquivB         : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    epsEstimateNTM        : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    revenueEstimateNTMB   : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    analystConsensus      : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    priceTargetConsensus  : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    closePrice1YrAgo      : gt(    null, 'price'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    liqCashRunwayQtrs     : gt(    null, 'liq'        , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    liqTotalLiquidityB    : gt(    null, 'liq'        , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
  },
  NVDA: {
    ticker: 'NVDA',
    marketCapB            : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    sharesOutstandingM    : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    peRatioTTM            : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    epsTTM                : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    dividendYield         : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    beta                  : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    revenueB              : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    grossMargin           : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    operatingMargin       : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    netMargin             : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    totalDebtB            : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    cashAndEquivB         : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    epsEstimateNTM        : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    revenueEstimateNTMB   : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    analystConsensus      : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    priceTargetConsensus  : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    closePrice1YrAgo      : gt(    null, 'price'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    liqCashRunwayQtrs     : gt(    null, 'liq'        , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    liqTotalLiquidityB    : gt(    null, 'liq'        , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
  },
  BIIB: {
    ticker: 'BIIB',
    marketCapB            : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    sharesOutstandingM    : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    peRatioTTM            : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    epsTTM                : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    dividendYield         : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    beta                  : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    revenueB              : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    grossMargin           : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    operatingMargin       : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    netMargin             : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    totalDebtB            : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    cashAndEquivB         : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    epsEstimateNTM        : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    revenueEstimateNTMB   : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    analystConsensus      : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    priceTargetConsensus  : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    closePrice1YrAgo      : gt(    null, 'price'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    liqCashRunwayQtrs     : gt(    null, 'liq'        , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    liqTotalLiquidityB    : gt(    null, 'liq'        , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
  },
  MRNA: {
    ticker: 'MRNA',
    marketCapB            : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    sharesOutstandingM    : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    peRatioTTM            : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    epsTTM                : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    dividendYield         : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    beta                  : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    revenueB              : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    grossMargin           : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    operatingMargin       : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    netMargin             : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    totalDebtB            : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    cashAndEquivB         : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    epsEstimateNTM        : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    revenueEstimateNTMB   : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    analystConsensus      : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    priceTargetConsensus  : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    closePrice1YrAgo      : gt(    null, 'price'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    liqCashRunwayQtrs     : gt(    null, 'liq'        , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    liqTotalLiquidityB    : gt(    null, 'liq'        , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
  },
  JPM: {
    ticker: 'JPM',
    marketCapB            : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    sharesOutstandingM    : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    peRatioTTM            : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    epsTTM                : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    dividendYield         : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    beta                  : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    revenueB              : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    grossMargin           : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    operatingMargin       : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    netMargin             : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    totalDebtB            : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    cashAndEquivB         : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    epsEstimateNTM        : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    revenueEstimateNTMB   : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    analystConsensus      : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    priceTargetConsensus  : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    closePrice1YrAgo      : gt(    null, 'price'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    liqCashRunwayQtrs     : gt(    null, 'liq'        , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    liqTotalLiquidityB    : gt(    null, 'liq'        , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
  },
  TSLA: {
    ticker: 'TSLA',
    marketCapB            : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    sharesOutstandingM    : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    peRatioTTM            : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    epsTTM                : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    dividendYield         : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    beta                  : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    revenueB              : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    grossMargin           : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    operatingMargin       : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    netMargin             : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    totalDebtB            : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    cashAndEquivB         : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    epsEstimateNTM        : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    revenueEstimateNTMB   : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    analystConsensus      : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    priceTargetConsensus  : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    closePrice1YrAgo      : gt(    null, 'price'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    liqCashRunwayQtrs     : gt(    null, 'liq'        , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    liqTotalLiquidityB    : gt(    null, 'liq'        , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
  },
  META: {
    ticker: 'META',
    marketCapB            : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    sharesOutstandingM    : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    peRatioTTM            : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    epsTTM                : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    dividendYield         : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    beta                  : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    revenueB              : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    grossMargin           : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    operatingMargin       : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    netMargin             : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    totalDebtB            : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    cashAndEquivB         : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    epsEstimateNTM        : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    revenueEstimateNTMB   : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    analystConsensus      : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    priceTargetConsensus  : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    closePrice1YrAgo      : gt(    null, 'price'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    liqCashRunwayQtrs     : gt(    null, 'liq'        , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    liqTotalLiquidityB    : gt(    null, 'liq'        , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
  },
  AMZN: {
    ticker: 'AMZN',
    marketCapB            : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    sharesOutstandingM    : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    peRatioTTM            : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    epsTTM                : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    dividendYield         : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    beta                  : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    revenueB              : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    grossMargin           : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    operatingMargin       : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    netMargin             : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    totalDebtB            : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    cashAndEquivB         : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    epsEstimateNTM        : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    revenueEstimateNTMB   : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    analystConsensus      : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    priceTargetConsensus  : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    closePrice1YrAgo      : gt(    null, 'price'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    liqCashRunwayQtrs     : gt(    null, 'liq'        , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    liqTotalLiquidityB    : gt(    null, 'liq'        , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
  },
  XOM: {
    ticker: 'XOM',
    marketCapB            : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    sharesOutstandingM    : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    peRatioTTM            : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    epsTTM                : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    dividendYield         : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    beta                  : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    revenueB              : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    grossMargin           : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    operatingMargin       : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    netMargin             : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    totalDebtB            : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    cashAndEquivB         : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    epsEstimateNTM        : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    revenueEstimateNTMB   : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    analystConsensus      : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    priceTargetConsensus  : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    closePrice1YrAgo      : gt(    null, 'price'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    liqCashRunwayQtrs     : gt(    null, 'liq'        , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    liqTotalLiquidityB    : gt(    null, 'liq'        , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
  },
  SPY: {
    ticker: 'SPY',
    marketCapB            : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    sharesOutstandingM    : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    peRatioTTM            : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    epsTTM                : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    dividendYield         : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    beta                  : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    revenueB              : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    grossMargin           : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    operatingMargin       : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    netMargin             : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    totalDebtB            : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    cashAndEquivB         : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    epsEstimateNTM        : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    revenueEstimateNTMB   : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    analystConsensus      : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    priceTargetConsensus  : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    closePrice1YrAgo      : gt(    null, 'price'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    liqCashRunwayQtrs     : gt(    null, 'liq'        , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    liqTotalLiquidityB    : gt(    null, 'liq'        , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
  },
  PLTR: {
    ticker: 'PLTR',
    marketCapB            : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    sharesOutstandingM    : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    peRatioTTM            : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    epsTTM                : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    dividendYield         : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    beta                  : gt(    null, 'ratio'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    revenueB              : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    grossMargin           : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    operatingMargin       : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    netMargin             : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    totalDebtB            : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    cashAndEquivB         : gt(    null, 'financial'  , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    epsEstimateNTM        : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    revenueEstimateNTMB   : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    analystConsensus      : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    priceTargetConsensus  : gt(    null, 'estimate'   , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    closePrice1YrAgo      : gt(    null, 'price'      , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    liqCashRunwayQtrs     : gt(    null, 'liq'        , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
    liqTotalLiquidityB    : gt(    null, 'liq'        , 'yahoo-seed'   , '2026-05-21', 'Yahoo fetch failed — fill manually'),
  },
}
// ── GROUND_TRUTH END ──
